name: Run JAR from Google Drive

on:  
  push:   
  workflow_dispatch:  

jobs:  
  run-jar:  
    runs-on: windows-latest
    steps:  
      - name: Checkout Repository  
        uses: actions/checkout@v4  

      - name: Download JAR from Google Drive  
        run: |  
          powershell -Command "Invoke-WebRequest -Uri 'https://drive.google.com/file/d/1djtkX3COrLDCGTPPhQ0TBwyYKADDeZzC/view?usp=sharing' -OutFile 'NoCodeBDD-V1-3-29.jar'"
      - name: Make JAR Executable  
        run: powershell -Command "chmod +x NoCodeBDD-V1-3-29.jar"  

      - name: Run JAR File  
        run: java -jar NoCodeBDD-V1-3-29.jar
