name: Run JAR from Google Drive

on:  
  push:   
  workflow_dispatch:  

jobs:  
  run-jar:  
    runs-on: windows-latest
    steps:  
      - name: Checkout Repository  
        uses: actions/checkout@v4  

      - name: Install gdown
        run: pip install gdown

      - name: Download JAR from Google Drive
        run: gdown "https://drive.google.com/uc?id=1djtkX3COrLDCGTPPhQ0TBwyYKADDeZzC" -O NoCodeBDD-V1-3-29.jar

      - name: Make JAR Executable  
        run: powershell -Command "chmod +x NoCodeBDD-V1-3-29.jar"  

      - name: Run JAR File with Timeout
        run: |
          Start-Process -NoNewWindow -FilePath "java" -ArgumentList "-jar NoCodeBDD-V1-3-29.jar" 
          Start-Sleep -Seconds 60
          Stop-Process -Name "java" -Force
  runi-jar:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Mockoon CLI
        run: npm install -g @mockoon/cli

      - name: Start Mockoon Mock APIs
        run: |
          Start-Process -NoNewWindow -FilePath "mockoon-cli" -ArgumentList "start --data ./Mockoon/ipt/IPTCoreMockService.json"
          Start-Process -NoNewWindow -FilePath "mockoon-cli" -ArgumentList "start --data ./Mockoon/ai-search/clientAiSearchService.json"

      - name: Verify Mockoon Processes
        run: powershell -Command "Get-Process | Where-Object { $_.ProcessName -match 'mockoon' }"
