name: Setup PostgreSQL Database on Windows

on:
  push:
  workflow_dispatch:

jobs:
  setup-postgres:
    runs-on: windows-latest

    steps:
      - name: Install PostgreSQL using Chocolatey
        run: |
          choco install postgresql -y --params "/Password:postgres"
        shell: powershell

      - name: Wait for PostgreSQL to start
        run: Start-Sleep -Seconds 30
        shell: powershell

      - name: Test Connection to PostgreSQL
        run: |
          $env:PGPASSWORD = "postgres"
          & "C:\Program Files\PostgreSQL\14\bin\psql.exe" -h localhost -U postgres -c "SELECT 1;"
        shell: powershell

      - name: Create Database client_protal
        run: |
          $env:PGPASSWORD = "postgres"
          & "C:\Program Files\PostgreSQL\14\bin\psql.exe" -h localhost -U postgres -c "CREATE DATABASE \"client_protal\";"
        shell: powershell

      - name: List Databases
        run: |
          $env:PGPASSWORD = "postgres"
          & "C:\Program Files\PostgreSQL\14\bin\psql.exe" -h localhost -U postgres -c "\l"
        shell: powershell
